### ISSUE TITLE
Add indent in json file

### ISSUE THREAD

**Issue by slawekstu** [credo-science/credo-api-tools#1]
I don't know if I'm writing proposals in the right place but..

Can you add indentations to all json files when downloading (detections, pins, mappings)?
Currently, there are no indentations, everything on 1 line which does not look good and is not convenient for quick browsing.

for example, in python, it is enough to give the following passage:
json.dump(json_object, json_file, **indent=4**)
where 
json_object is a single record
json_file - file in which we want to save

Below is 
**the current record, e.g. in detection**
{"user_id": 14269, "latitude": -#####, "timestamp": 1554139941570, "altitude": ####, "visible": false, "longitude": ####, "height": ###, "frame_content": "very long text.", "width": 1920, "team_id": 2370, "source": "api_v2", "provider": "gps", "y": 0, "x": 1174, "device_id": 9918, "id": 9635516, "time_received": 1554139943243, "accuracy": ####},

**my proposition:**
  {
            "user_id": 14269,
            "latitude": -####,
            "timestamp": 1554139941570,
            "altitude": ###,
            "visible": false,
            "longitude": ####,
            "height": ###,
            "frame_content": "very long text",
            "width": 1920,
            "team_id": 2370,
            "source": "api_v2",
            "provider": "gps",
            "y": 0,
            "x": 1174,
            "device_id": 9918,
            "id": 9635516,
            "time_received": 1554139943243,
            "accuracy": ####
        }

I used the "#" sign to not show sensitive data

**Comment by koziomek** [comment]
Exported files are not meant to be read directly by humans.

I recommend using jq (https://stedolan.github.io/jq/) for exploring json files.

Example of pretty-printing file:

`$ jq '.' file.json`
